variables:
- name: SolutionBaseName
  value: Dfc.DevOps

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: olusola-adio/dfc-devops
    endpoint: 'olusola-adio'
    ref: refs/tags/v1.9.0

pool:
  name: ubuntu-16.04
  demands:
    - PowerShell
    - AzurePS
    - docker

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master


stages:
- template: StageTemplates/RunTests.yml
  parameters:
    AzureSubscription: 'Visual Studio Enterprise Subscription – MPN (d28ae51b-c7ef-41b3-8ee0-644dac2b5152)'
    Powershell5CodeCoveragePercentage: 45
    PowershellCoreCodeCoveragePercentage: 25

- stage: BuildAndPublishContainers
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: []
  variables:
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\BuildAndPublishLinuxContainers.yml
    parameters:
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)

- stage: DeployAzureDevOpsContainers
  condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: BuildAndPublishContainers
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\DevEnvironmentVariables.yml
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  - group: dfc-devops-dev
  jobs:
  - template: JobTemplates\DeployContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzurePatToken: $(AzureDevOpsAgentPatToken)
      AzureSubscriptionEndpoint: 'Visual Studio Enterprise Subscription – MPN (d28ae51b-c7ef-41b3-8ee0-644dac2b5152)'
      Environment: DEV_SHARED
      KubernetesCluster: $(sharedAksCluster)