variables:
- name: SolutionBaseName
  value: Dfc.DevOps

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: olusola-adio/dfc-devops
    endpoint: 'olusola-adio'
    ref: refs/tags/v1.8.5

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:

- stage: Test
  jobs:
  - template: JobTemplates\Test.yml
    parameters:
      AzureSubscription: 'Visual Studio Enterprise Subscription – MPN (d28ae51b-c7ef-41b3-8ee0-644dac2b5152)'
      CodeCoveragePercentage: 45

- stage: BuildAndPublishContainers
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: []
  variables:
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\BuildAndPublishLinuxContainers.yml
    parameters:
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ContainerRegistryPassword: $(ContainerRegistryPassword)

- stage: DeployAzureDevOpsContainers
  condition: and(succeeded('BuildAndPublishContainers'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: BuildAndPublishContainers
  variables:
  - template: VariableTemplates\SharedEnvironmentVariables.yml
  - template: VariableTemplates\DevEnvironmentVariables.yml
  - group: KeyVault - dfc-dev-shared-kv
  - group: dfc-shared-dev
  jobs:
  - template: JobTemplates\DeployContainers.yml
    parameters:
      AksResourceGroup: $(sharedResourceGroup)
      AzureSubscriptionEndpoint: 'Visual Studio Enterprise Subscription – MPN (d28ae51b-c7ef-41b3-8ee0-644dac2b5152)'
      Environment: DEV_SHARED
      KubernetesCluster: $(sharedAksCluster)